### PR TITLE
Invoice repository

### PR DESCRIPTION
**Pull request by alexGrandolph**
In this pull request:
- Add spec tests for new Invoice and InvoiceRepository classes
- Add all classes and methods for Invoice and InvoiceRepository 
- BigDecimal

### CODE REVIEW

**Comment by alexGrandolph** [comment]
really good job! very impressive stuff

**Comment by James-Harkins** [comment]
Killin' it fam

**Comment by CLRM1** [comment]
Excellent work with the TDD flow!

**Comment by amsalmeron** [comment]
Moving forward, let the refactoring begin!

**Pull request merged**
