### PR TITLE
Merchant repository

### PR DESCRIPTION
**Pull request by James-Harkins**
The Merchant Repository class is now passing all Iteration 0 tests.

### CODE REVIEW

**Review by CLRM1 — APPROVED** [review]

**Comment by alexGrandolph** [comment]
Thank you Meg!

**Comment by alexGrandolph** [comment]
Meg can do what the Hound wishes it could do!

**Comment by CLRM1** [comment]
Great refactor!

**Comment by amsalmeron** [comment]
This looks good!

**Pull request merged**
