### PR TITLE
Item repository

### PR DESCRIPTION
**Pull request by alexGrandolph**
- add ItemRepository class
- add tests for all corresponding methods for ItemRepository
- add code to pass all tests

### CODE REVIEW

**Comment by alexGrandolph** [comment]
great use of BigDecimal

**Comment by amsalmeron** [comment]
Time.now works like a charm!

**Comment by James-Harkins** [comment]
We beat the Hound

**Comment by CLRM1** [comment]
Should we look into the hound's comments?

**Pull request merged**
